2021-08-26 06:58:14,495 INFO    MainThread:20289 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 06:58:14,496 INFO    MainThread:20289 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 06:58:14,496 INFO    MainThread:20289 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_065814-3vgxsdgb/logs/debug.log
2021-08-26 06:58:14,496 INFO    MainThread:20289 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_065814-3vgxsdgb/logs/debug-internal.log
2021-08-26 06:58:14,497 INFO    MainThread:20289 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9389e79c70>
2021-08-26 06:58:14,498 INFO    MainThread:20289 [wandb_init.py:init():375] calling init triggers
2021-08-26 06:58:14,498 INFO    MainThread:20289 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-26 06:58:14,498 INFO    MainThread:20289 [wandb_init.py:init():395] re-initializing run, found existing run on stack: z3s65q3z
2021-08-26 06:58:14,499 INFO    MainThread:20289 [wandb_run.py:finish():1254] finishing run presto105/lv1_p/z3s65q3z
2021-08-26 06:58:14,595 INFO    MainThread:20289 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-26 06:58:14,595 INFO    MainThread:20289 [wandb_run.py:_restore():1526] restore
2021-08-26 06:58:14,817 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 06:58:15,042 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 1081
}

2021-08-26 06:58:15,750 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9752
}

2021-08-26 06:58:15,853 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9780
}

2021-08-26 06:58:15,956 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9780
}

2021-08-26 06:58:16,058 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1081
  total_bytes: 9780
}

2021-08-26 06:58:16,159 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:16,262 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:16,364 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:16,466 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:16,568 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:16,966 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:17,068 INFO    MainThread:20289 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9780
  total_bytes: 9780
}

2021-08-26 06:58:18,197 INFO    MainThread:20289 [wandb_run.py:_show_files():1898] logging synced files
2021-08-26 06:58:18,201 INFO    MainThread:20289 [wandb_init.py:init():424] starting backend
2021-08-26 06:58:18,202 INFO    MainThread:20289 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-26 06:58:18,204 INFO    MainThread:20289 [backend.py:ensure_launched():135] starting backend process...
2021-08-26 06:58:18,236 INFO    MainThread:20289 [backend.py:ensure_launched():139] started backend process with pid: 21399
2021-08-26 06:58:18,239 INFO    MainThread:20289 [wandb_init.py:init():429] backend started and connected
2021-08-26 06:58:18,257 INFO    MainThread:20289 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-26 06:58:18,258 INFO    MainThread:20289 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-26 06:58:18,258 INFO    MainThread:20289 [wandb_init.py:init():477] updated telemetry
2021-08-26 06:58:18,259 INFO    MainThread:20289 [wandb_init.py:init():500] communicating current version
2021-08-26 06:58:19,088 INFO    MainThread:20289 [wandb_init.py:init():505] got version response 
2021-08-26 06:58:19,088 INFO    MainThread:20289 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-26 06:58:19,311 INFO    MainThread:20289 [wandb_init.py:init():540] starting run threads in backend
2021-08-26 06:58:23,786 INFO    MainThread:20289 [wandb_run.py:_console_start():1584] atexit reg
2021-08-26 06:58:23,788 INFO    MainThread:20289 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-26 06:58:23,788 INFO    MainThread:20289 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-26 06:58:23,789 INFO    MainThread:20289 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-26 06:58:23,789 INFO    MainThread:20289 [wandb_init.py:init():565] run started, returning control to user process
2021-08-26 06:58:23,790 INFO    MainThread:20289 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-26 06:58:23,790 INFO    MainThread:20289 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 06:58:48,764 INFO    MainThread:20289 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-26 06:58:48,766 INFO    MainThread:20289 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-26 06:58:48,766 INFO    MainThread:20289 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 06:58:51,893 INFO    MainThread:20289 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-26 06:58:51,895 INFO    MainThread:20289 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-26 06:58:51,895 INFO    MainThread:20289 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-26 06:58:52,642 INFO    MainThread:20289 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-26 06:58:52,650 INFO    MainThread:20289 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 06:58:52,650 INFO    MainThread:20289 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 06:58:52,650 INFO    MainThread:20289 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_065852-vtudew78/logs/debug.log
2021-08-26 06:58:52,650 INFO    MainThread:20289 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/image-classification-level1-25/wandb/run-20210826_065852-vtudew78/logs/debug-internal.log
2021-08-26 06:58:52,651 INFO    MainThread:20289 [wandb_init.py:init():375] calling init triggers
2021-08-26 06:58:52,651 INFO    MainThread:20289 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-26 06:58:52,651 INFO    MainThread:20289 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3vgxsdgb
2021-08-26 06:58:52,652 INFO    MainThread:20289 [wandb_run.py:finish():1254] finishing run presto105/lv1_p/3vgxsdgb
